# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:23
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170227_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
